name: Run tests

on: [push]

jobs:
  build:

    strategy:
      matrix:
        node-version: [12.x]
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - name: Run tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run test
